version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest   # (1)
    working_directory: /go/src/circleci-demo-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      # ... steps for building/testing app ...

      # - setup_remote_docker:   # (2)
      #     docker_layer_caching: true # (3)

      # # use a primary image that already has Docker (recommended)
      # # or install it during a build like we do here
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="18.06.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          ls
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   $DOCKER_USER/circleci-demo-docker:$TAG cmd/prombench/Dockerfile     
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
          docker push $DOCKER_USER/circleci-demo-docker:$TAG